name: OX JS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # Every hour

permissions:
  contents: write

jobs:
  update-cleaned-js:
    runs-on: ubuntu-latest

    steps:
      - name: Crescendo
        uses: actions/checkout@v3

      - name: Fetch OX JS from Gist
        run: |
          curl -s https://gist.githubusercontent.com/aamiaa/204cd9d42013ded9faf646fae7f89fbb/raw/cc791c930278f12f28eeac6de96c89e91c39c499/ > full.txt

          awk '/^```js/{flag=1; next} /^```/{flag=0} flag' full.txt > cleaned.js

      - name: Set up config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push OX JS
        run: |
          git add ox.js
          git diff --cached --quiet || git commit -m "update OX JS"
          git push
